In [1]:
# !pip install plotly==5.3.1

In [2]:
# !pip install addfips
# or
# pip install --user addfips

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas
import addfips

In [4]:

annual_aqi = pd.DataFrame()
for n in range(2000, 2021):
    annual_aqi_n = pd.read_csv(f'annual_aqi_by_country/annual_aqi_by_county_{n}.csv')
    annual_aqi = pd.concat([annual_aqi, annual_aqi_n], axis=0)
annual_aqi.head()

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Baldwin,2000,257,111,96,39,10,1,0,205,129,54,0,0,215,0,42,0
1,Alabama,Clay,2000,271,155,101,14,1,0,0,177,90,46,0,0,188,0,83,0
2,Alabama,Colbert,2000,358,273,78,7,0,0,0,124,67,16,0,0,0,260,98,0
3,Alabama,DeKalb,2000,354,169,123,58,4,0,0,159,115,51,0,0,297,0,56,1
4,Alabama,Elmore,2000,242,125,78,37,2,0,0,166,112,50,0,0,242,0,0,0

In [5]:
take_out = ['Virgin Islands', 'Country Of Mexico', 'Canada', 'Puerto Rico']
annual_aqi = annual_aqi[~annual_aqi['State'].isin(take_out)]
annual_aqi

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Baldwin,2000,257,111,96,39,10,1,0,205,129,54,0,0,215,0,42,0
1,Alabama,Clay,2000,271,155,101,14,1,0,0,177,90,46,0,0,188,0,83,0
2,Alabama,Colbert,2000,358,273,78,7,0,0,0,124,67,16,0,0,0,260,98,0
3,Alabama,DeKalb,2000,354,169,123,58,4,0,0,159,115,51,0,0,297,0,56,1
4,Alabama,Elmore,2000,242,125,78,37,2,0,0,166,112,50,0,0,242,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,Wyoming,Sublette,2020,366,297,64,4,1,0,0,151,61,44,0,0,355,0,11,0
1036,Wyoming,Sweetwater,2020,366,238,116,7,4,0,1,1250,76,46,0,5,253,0,7,101
1037,Wyoming,Teton,2020,366,318,36,7,5,0,0,161,54,42,0,0,329,0,37,0
1038,Wyoming,Uinta,2020,366,323,41,2,0,0,0,122,51,40,0,2,225,0,0,139
1039,Wyoming,Weston,2020,366,336,29,1,0,0,0,119,49,40,0,0,353,13,0,0

In [6]:
annual_aqi['County'] = annual_aqi['County'].str.lower()

annual_aqi['County'].unique()

array(['baldwin', 'clay', 'colbert', 'dekalb', 'elmore', 'escambia',
       'etowah', 'houston', 'jackson', 'jefferson', 'lawrence', 'madison',
       'marengo', 'mobile', 'montgomery', 'morgan', 'pike', 'russell',
       'shelby', 'sumter', 'talladega', 'tuscaloosa', 'walker',
       'anchorage ', 'denali ', 'fairbanks north star ', 'juneau ',
       'ketchikan gateway ', 'matanuska-susitna ', 'apache', 'cochise',
       'coconino', 'gila', 'graham', 'maricopa', 'mohave', 'navajo',
       'pima', 'pinal', 'santa cruz', 'yavapai', 'yuma', 'arkansas',
       'ashley', 'clark', 'craighead', 'crittenden', 'faulkner',
       'garland', 'marion', 'miller', 'mississippi', 'newton', 'phillips',
       'polk', 'pope', 'pulaski', 'sebastian', 'union', 'washington',
       'white', 'alameda', 'amador', 'butte', 'calaveras', 'colusa',
       'contra costa', 'del norte', 'el dorado', 'fresno', 'glenn',
       'humboldt', 'imperial', 'inyo', 'kern', 'kings', 'lake', 'lassen',
       'los angeles', 'madera', 'marin', 'mariposa', 'mendocino',
       'merced', 'modoc', 'mono', 'monterey', 'napa', 'nevada', 'orange',
       'placer', 'plumas', 'riverside', 'sacramento', 'san benito',
       'san bernardino', 'san diego', 'san francisco', 'san joaquin',
       'san luis obispo', 'san mateo', 'santa barbara', 'santa clara',
       'shasta', 'sierra', 'siskiyou', 'solano', 'sonoma', 'stanislaus',
       'sutter', 'tehama', 'trinity', 'tulare', 'tuolumne', 'ventura',
       'yolo', 'adams', 'alamosa', 'arapahoe', 'archuleta', 'boulder',
       'delta', 'denver', 'douglas', 'eagle', 'el paso', 'elbert',
       'fremont', 'garfield', 'gunnison', 'la plata', 'larimer', 'mesa',
       'montezuma', 'montrose', 'pitkin', 'prowers', 'pueblo', 'routt',
       'san juan', 'san miguel', 'summit', 'teller', 'weld', 'fairfield',
       'hartford', 'litchfield', 'middlesex', 'new haven', 'new london',
       'tolland', 'windham', 'kent', 'new castle', 'sussex',
       'district of columbia', 'alachua', 'baker', 'bay', 'brevard',
       'broward', 'citrus', 'collier', 'columbia', 'duval', 'hamilton',
       'hillsborough', 'holmes', 'lee', 'leon', 'liberty', 'manatee',
       'miami-dade', 'monroe', 'nassau', 'osceola', 'palm beach', 'pasco',
       'pinellas', 'putnam', 'santa rosa', 'sarasota', 'seminole',
       'st. lucie', 'volusia', 'wakulla', 'bartow', 'bibb', 'charlton',
       'chatham', 'chattooga', 'cherokee', 'clarke', 'clayton', 'cobb',
       'coweta', 'dawson', 'dougherty', 'fannin', 'fayette', 'floyd',
       'fulton', 'glynn', 'gwinnett', 'hall', 'henry', 'lowndes',
       'murray', 'muscogee', 'paulding', 'richmond', 'rockdale',
       'spalding', 'wilkinson', 'hawaii', 'honolulu', 'kauai', 'maui',
       'ada', 'bannock', 'benewah', 'bingham', 'bonner', 'bonneville',
       'boundary', 'canyon', 'caribou', 'custer', 'kootenai', 'lemhi',
       'lewis', 'minidoka', 'nez perce', 'power', 'shoshone',
       'twin falls', 'champaign', 'cook', 'dupage', 'effingham', 'jersey',
       'jo daviess', 'kane', 'la salle', 'macon', 'macoupin', 'mchenry',
       'mclean', 'peoria', 'randolph', 'rock island', 'saint clair',
       'sangamon', 'tazewell', 'wabash', 'will', 'winnebago', 'allen',
       'bartholomew', 'boone', 'daviess', 'dearborn', 'delaware',
       'dubois', 'elkhart', 'fountain', 'gibson', 'greene', 'hancock',
       'hendricks', 'howard', 'huntington', 'jasper', 'johnson', 'knox',
       'laporte', 'perry', 'porter', 'posey', 'spencer', 'st. joseph',
       'sullivan', 'tippecanoe', 'vanderburgh', 'vigo', 'warrick',
       'wayne', 'black hawk', 'bremer', 'cerro gordo', 'clinton', 'emmet',
       'harrison', 'linn', 'muscatine', 'palo alto', 'pottawattamie',
       'scott', 'story', 'van buren', 'warren', 'woodbury', 'ford',
       'neosho', 'sedgwick', 'shawnee', 'sherman', 'sumner', 'trego',
       'wyandotte', 'bell', 'boyd', 'bullitt', 'campbell', 'carter',
       'christian', 'edmonson', 'franklin', 'graves', 'greenup', 'hardin',
       'harlan', 'henderson', 'jessamine', 'kenton', 'livingston',
       'marshall', 'mccracken', 'oldham', 'simpson', 'trigg', 'whitley',
       'ascension', 'beauregard', 'bossier', 'caddo', 'calcasieu',
       'concordia', 'east baton rouge', 'grant', 'iberville', 'lafayette',
       'lafourche', 'orleans', 'ouachita', 'plaquemines', 'pointe coupee',
       'rapides', 'st. bernard', 'st. charles', 'st. james',
       'st. john the baptist', 'st. mary', 'tangipahoa', 'terrebonne',
       'west baton rouge', 'androscoggin', 'aroostook', 'cumberland',
       'kennebec', 'mobile monitors', 'oxford', 'penobscot',
       'piscataquis', 'sagadahoc', 'york', 'anne arundel', 'baltimore',
       'baltimore (city)', 'calvert', 'carroll', 'cecil', 'charles',
       'dorchester', 'frederick', 'harford', "prince george's",
       'wicomico', 'barnstable', 'berkshire', 'bristol', 'essex',
       'hampden', 'hampshire', 'norfolk', 'plymouth', 'suffolk',
       'worcester', 'allegan', 'alpena', 'benzie', 'berrien', 'calhoun',
       'cass', 'genesee', 'grand traverse', 'huron', 'ingham',
       'kalamazoo', 'keweenaw', 'lenawee', 'macomb', 'manistee', 'mason',
       'missaukee', 'muskegon', 'oakland', 'ottawa', 'saginaw',
       'schoolcraft', 'st. clair', 'tuscola', 'washtenaw', 'wexford',
       'anoka', 'carlton', 'crow wing', 'dakota', 'freeborn', 'hennepin',
       'itasca', 'kandiyohi', 'koochiching', 'mcleod', 'mille lacs',
       'nicollet', 'olmsted', 'otter tail', 'pine', 'ramsey',
       'saint louis', 'stearns', 'wright', 'bolivar', 'desoto', 'forrest',
       'hinds', 'jones', 'lauderdale', 'pearl river', 'rankin',
       'yalobusha', 'buchanan', 'cedar', 'howell', 'iron', 'lincoln',
       'mercer', 'platte', 'saint charles', 'sainte genevieve',
       'st. louis city', 'stoddard', 'cascade', 'fergus', 'flathead',
       'gallatin', 'glacier', 'lewis and clark', 'missoula', 'powell',
       'ravalli', 'roosevelt', 'rosebud', 'sanders', 'sheridan',
       'silver bow', 'yellowstone', 'cherry', 'deuel', 'lancaster',
       'sarpy', 'scotts bluff', 'carson city', 'elko', 'lander', 'washoe',
       'white pine', 'belknap', 'cheshire', 'coos', 'grafton',
       'merrimack', 'rockingham', 'strafford', 'atlantic', 'bergen',
       'burlington', 'camden', 'gloucester', 'hudson', 'hunterdon',
       'monmouth', 'morris', 'ocean', 'passaic', 'bernalillo', 'catron',
       'chaves', 'dona ana', 'eddy', 'hidalgo', 'lea', 'los alamos',
       'luna', 'otero', 'rio arriba', 'sandoval', 'santa fe', 'socorro',
       'taos', 'valencia', 'albany', 'bronx', 'broome', 'chautauqua',
       'chemung', 'dutchess', 'erie', 'herkimer', 'new york', 'niagara',
       'oneida', 'onondaga', 'queens', 'rensselaer', 'saratoga',
       'schenectady', 'st. lawrence', 'steuben', 'tompkins', 'ulster',
       'westchester', 'alamance', 'alexander', 'avery', 'beaufort',
       'buncombe', 'cabarrus', 'caldwell', 'carteret', 'caswell',
       'catawba', 'davidson', 'davie', 'duplin', 'durham', 'edgecombe',
       'forsyth', 'gaston', 'granville', 'guilford', 'harnett', 'haywood',
       'hyde', 'johnston', 'lenoir', 'martin', 'mcdowell', 'mecklenburg',
       'mitchell', 'new hanover', 'northampton', 'onslow', 'pasquotank',
       'person', 'pitt', 'robeson', 'rowan', 'swain', 'wake', 'yancey',
       'billings', 'burke', 'burleigh', 'dunn', 'grand forks', 'mckenzie',
       'morton', 'oliver', 'stark', 'steele', 'williams', 'ashtabula',
       'athens', 'belmont', 'butler', 'clermont', 'columbiana',
       'crawford', 'cuyahoga', 'geauga', 'licking', 'lorain', 'lucas',
       'mahoning', 'medina', 'meigs', 'miami', 'noble', 'portage',
       'preble', 'richland', 'sandusky', 'scioto', 'seneca', 'trumbull',
       'tuscarawas', 'wood', 'wyandot', 'canadian', 'cleveland',
       'comanche', 'kay', 'latimer', 'love', 'mayes', 'mcclain',
       'muskogee', 'oklahoma', 'osage', 'pawnee', 'payne', 'pittsburg',
       'pottawatomie', 'tulsa', 'benton', 'clackamas', 'deschutes',
       'harney', 'josephine', 'klamath', 'lane', 'multnomah', 'umatilla',
       'wallowa', 'wasco', 'allegheny', 'armstrong', 'beaver', 'berks',
       'blair', 'bucks', 'cambria', 'centre', 'chester', 'clearfield',
       'dauphin', 'elk', 'lackawanna', 'lehigh', 'luzerne', 'lycoming',
       'philadelphia', 'schuylkill', 'somerset', 'tioga', 'westmoreland',
       'providence', 'abbeville', 'aiken', 'anderson', 'barnwell',
       'berkeley', 'charleston', 'chesterfield', 'colleton', 'darlington',
       'edgefield', 'florence', 'georgetown', 'greenville', 'greenwood',
       'horry', 'lexington', 'oconee', 'pickens', 'spartanburg',
       'williamsburg', 'brookings', 'brown', 'minnehaha', 'pennington',
       'blount', 'bradley', 'claiborne', 'dickson', 'dyer', 'hawkins',
       'humphreys', 'maury', 'mcminn', 'roane', 'rutherford', 'sevier',
       'stewart', 'williamson', 'wilson', 'bexar', 'bowie', 'brazoria',
       'brewster', 'cameron', 'collin', 'culberson', 'dallas', 'denton',
       'ector', 'ellis', 'galveston', 'gregg', 'harris', 'hood',
       'kaufman', 'lubbock', 'mclennan', 'nueces', 'parker', 'potter',
       'rockwall', 'smith', 'tarrant', 'travis', 'victoria', 'webb',
       'box elder', 'cache', 'davis', 'grand', 'salt lake', 'tooele',
       'uintah', 'utah', 'weber', 'bennington', 'chittenden', 'rutland',
       'alexandria city', 'arlington', 'bristol city', 'caroline',
       'charlottesville city', 'chesapeake city', 'culpeper', 'fairfax',
       'fauquier', 'fredericksburg city', 'giles', 'hampton city',
       'henrico', 'king william', 'loudoun', 'lynchburg city',
       'newport news city', 'norfolk city', 'northumberland', 'page',
       'prince edward', 'prince william', 'richmond city', 'roanoke',
       'roanoke city', 'rockbridge', 'salem city', 'stafford',
       'suffolk city', 'virginia beach city', 'winchester city', 'wise',
       'wythe', 'asotin', 'chelan', 'clallam', 'cowlitz', 'king',
       'kitsap', 'kittitas', 'klickitat', 'pierce', 'skagit', 'snohomish',
       'spokane', 'stevens', 'thurston', 'walla walla', 'whatcom',
       'whitman', 'yakima', 'brooke', 'cabell', 'gilmer', 'greenbrier',
       'kanawha', 'monongalia', 'ohio', 'raleigh', 'summers', 'tucker',
       'dane', 'dodge', 'door', 'fond du lac', 'green', 'kenosha',
       'kewaunee', 'manitowoc', 'marathon', 'milwaukee', 'outagamie',
       'ozaukee', 'racine', 'rock', 'sauk', 'sheboygan', 'st. croix',
       'taylor', 'vernon', 'vilas', 'walworth', 'waukesha', 'carbon',
       'converse', 'laramie', 'natrona', 'park', 'sublette', 'sweetwater',
       'teton', 'aleutians east ', 'kenai peninsula ', 'highlands',
       'indian river', 'muhlenberg', 'winn', 'chippewa', 'alcorn',
       'maries', 'taney', 'stillwater', 'sweet grass', 'watauga',
       'gallia', 'meade', 'roberts', 'hamblen', 'obion', 'hanover',
       'okanogan', 'ashland', 'coffee', 'boise', 'idaho', 'latah',
       'valley', 'chase', 'riley', 'laurel', 'winona', 'grenada',
       'cooper', 'big horn', 'musselshell', 'garden', 'thomas', 'oswego',
       'adair', 'dewey', 'orangeburg', 'jeff davis', 'duchesne',
       'grays harbor', 'skamania', 'eau claire', 'forest', 'barbour',
       'limestone', 'kosciusko', 'leavenworth', 'dukes', 'leelanau',
       'goodhue', 'mineral', 'nye', 'nash', 'cotton', 'creek',
       'codington', 'loudon', 'hays', 'hunt', 'kleberg', 'addison',
       'northwest arctic ', 'skagway-hoonah-angoon',
       'wrangell petersburg', 'gem', 'garrett', 'mccone', 'sequoyah',
       'indiana', 'waupaca', 'la paz', 'walton', 'st. tammany',
       'dickinson', 'becker', 'lyon', 'churchill', 'maverick', 'wichita',
       'la crosse', 'weston', 'hopewell city', 'pend oreille',
       'clear creek', 'larue', 'presque isle', 'webster', 'sioux',
       'randall', 'uinta', 'yukon-koyukuk ', 'okaloosa', 'mckinley',
       'crook', 'yamhill', 'albemarle', 'chaffee', 'logan', 'andrew',
       'callaway', 'rockland', 'ward', 'navarro', 'rio blanco', 'cassia',
       'tama', 'powder river', 'mccurtain', 'daggett', 'alpine', 'moffat',
       'flagler', 'lebanon', 'gillespie', 'barron', 'bryan', 'bradford',
       'trempealeau', 'beltrami', 'goshen', 'blaine', 'jerome',
       'st. martin', 'stutsman', 'hughes', 'brunswick', 'grady',
       'hutchinson', 'milam', 'robertson', 'titus', 'allegany',
       'new madrid', 'choctaw', 'freestone', 'rusk', 'botetourt',
       'covington city', 'bethel ', 'le flore', 'nowata', 'susquehanna',
       'north slope ', 'gilpin', 'wyoming', 'guernsey', 'atascosa',
       'brazos', 'karnes'], dtype=object)

In [7]:
# fips = pd.read_csv('fips-codes-master/state_and_county_fips_master.csv')
fips_rows = []
for i, row in annual_aqi.iterrows():
    fips_row = {
        'County': row['County'],
        'State': row['State']
    }
    fips_rows.append(fips_row)

fips_rows[:5]
# fips

[{'County': 'baldwin', 'State': 'Alabama'},
 {'County': 'clay', 'State': 'Alabama'},
 {'County': 'colbert', 'State': 'Alabama'},
 {'County': 'dekalb', 'State': 'Alabama'},
 {'County': 'elmore', 'State': 'Alabama'}]

In [8]:
# code from https://pypi.org/project/addfips/

af = addfips.AddFIPS()
for row in fips_rows:
    af.add_county_fips(row, county_field='County', state_field='State')
    
fips_rows[:5]

[{'County': 'baldwin', 'State': 'Alabama', 'fips': '01003'},
 {'County': 'clay', 'State': 'Alabama', 'fips': '01027'},
 {'County': 'colbert', 'State': 'Alabama', 'fips': '01033'},
 {'County': 'dekalb', 'State': 'Alabama', 'fips': '01049'},
 {'County': 'elmore', 'State': 'Alabama', 'fips': '01051'}]

In [9]:
fips = pd.DataFrame(fips_rows)
fips

           County    State   fips
0         baldwin  Alabama  01003
1            clay  Alabama  01027
2         colbert  Alabama  01033
3          dekalb  Alabama  01049
4          elmore  Alabama  01051
...           ...      ...    ...
22626    sublette  Wyoming  56035
22627  sweetwater  Wyoming  56037
22628       teton  Wyoming  56039
22629       uinta  Wyoming  56041
22630      weston  Wyoming  56045

[22631 rows x 3 columns]

In [10]:
fips.isna().sum()

County      0
State       0
fips      237
dtype: int64

In [11]:
fips[fips['fips'].isna()]['State'].value_counts()

Alaska      169
Illinois     21
Maryland     21
Virginia     21
Maine         5
Name: State, dtype: int64

In [12]:
# fips.drop(index=0, inplace=True)
# # fips.rename(columns={'state': 'state_abrv', 'name': 'County'}, inplace=True)
# fips['County'].replace(r' County', '', regex=True, inplace=True)
# fips['County'].replace(r' Borough', '', regex=True, inplace=True)
# fips['County'].replace(r' and', '', regex=True, inplace=True)
# fips['County'].replace(r' And', '', regex=True, inplace=True)
# fips['County'].replace(r' City', '', regex=True, inplace=True)
# fips['County'].replace(r' Census Area', '', regex=True, inplace=True)
# fips['County'].replace(r' Municipality', '', regex=True, inplace=True)
# fips['County'].replace(r'\.', '', regex=True, inplace=True)
# fips.dropna(inplace=True)
# fips

In [13]:
annual_aqi['County'] = annual_aqi['County'].str.lower()
fips['County'] = fips['County'].str.lower()
annual_aqi

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,baldwin,2000,257,111,96,39,10,1,0,205,129,54,0,0,215,0,42,0
1,Alabama,clay,2000,271,155,101,14,1,0,0,177,90,46,0,0,188,0,83,0
2,Alabama,colbert,2000,358,273,78,7,0,0,0,124,67,16,0,0,0,260,98,0
3,Alabama,dekalb,2000,354,169,123,58,4,0,0,159,115,51,0,0,297,0,56,1
4,Alabama,elmore,2000,242,125,78,37,2,0,0,166,112,50,0,0,242,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,Wyoming,sublette,2020,366,297,64,4,1,0,0,151,61,44,0,0,355,0,11,0
1036,Wyoming,sweetwater,2020,366,238,116,7,4,0,1,1250,76,46,0,5,253,0,7,101
1037,Wyoming,teton,2020,366,318,36,7,5,0,0,161,54,42,0,0,329,0,37,0
1038,Wyoming,uinta,2020,366,323,41,2,0,0,0,122,51,40,0,2,225,0,0,139
1039,Wyoming,weston,2020,366,336,29,1,0,0,0,119,49,40,0,0,353,13,0,0

In [14]:
annual_aqi = annual_aqi[annual_aqi['Year'] >=2005]

In [15]:
# aqi_fips = annual_aqi.merge(fips, how='left', left_on='County', right_on='County', copy=False).drop_duplicates(['County', 'Year', 'Max AQI'])
# aqi_fips.reset_index(inplace=True)
# aqi_fips

In [16]:
ak_fips = fips[fips['State'] == 'Alaska']
ak_fips

                      County   State  fips
23                anchorage   Alaska  None
24                   denali   Alaska  None
25     fairbanks north star   Alaska  None
26                   juneau   Alaska  None
27        ketchikan gateway   Alaska  None
...                      ...     ...   ...
21626  fairbanks north star   Alaska  None
21627                juneau   Alaska  None
21628       kenai peninsula   Alaska  None
21629     matanuska-susitna   Alaska  None
21630           north slope   Alaska  None

[169 rows x 3 columns]

In [17]:
# aqi_fips[(aqi_fips['fips_y'].isna()) & (aqi_fips['State'] == 'Alaska')]

In [18]:
# fips[fips['state_abrv'] == 'AK']['County'].value_counts()

In [19]:
# aqi_fips[aqi_fips['State'] == 'Alaska']['County'].value_counts()

In [20]:
# fips_rows = []
# for i, row in annual_aqi.iterrows():
#     fips_row = {
#         'County': row['County'],
#         'State': row['State']
#     }
#     fips_rows.append(fips_row)

# fips_rows[:5]

In [21]:
# code from https://pypi.org/project/addfips/

# af = addfips.AddFIPS()
# for row in fips_rows:
#     af.add_county_fips(row, county_field='County', state_field='State')
    
# fips_rows[:5]

In [22]:
# fips = pd.DataFrame(fips_rows)
fips

           County    State   fips
0         baldwin  Alabama  01003
1            clay  Alabama  01027
2         colbert  Alabama  01033
3          dekalb  Alabama  01049
4          elmore  Alabama  01051
...           ...      ...    ...
22626    sublette  Wyoming  56035
22627  sweetwater  Wyoming  56037
22628       teton  Wyoming  56039
22629       uinta  Wyoming  56041
22630      weston  Wyoming  56045

[22631 rows x 3 columns]

In [23]:
# annual_aqi.shape

In [24]:
# annual_aqi.loc[:,'County'] = annual_aqi.loc[:,'County'].str.lower()
annual_aqi

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,baldwin,2005,254,158,86,10,0,0,0,147,80,46,0,0,171,0,83,0
1,Alabama,barbour,2005,59,35,23,1,0,0,0,119,68,47,0,0,0,0,59,0
2,Alabama,clay,2005,282,176,96,10,0,0,0,136,84,46,0,0,191,0,91,0
3,Alabama,colbert,2005,365,255,100,10,0,0,0,126,75,43,0,0,188,94,83,0
4,Alabama,dekalb,2005,358,248,102,8,0,0,0,140,74,43,0,0,275,0,83,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,Wyoming,sublette,2020,366,297,64,4,1,0,0,151,61,44,0,0,355,0,11,0
1036,Wyoming,sweetwater,2020,366,238,116,7,4,0,1,1250,76,46,0,5,253,0,7,101
1037,Wyoming,teton,2020,366,318,36,7,5,0,0,161,54,42,0,0,329,0,37,0
1038,Wyoming,uinta,2020,366,323,41,2,0,0,0,122,51,40,0,2,225,0,0,139
1039,Wyoming,weston,2020,366,336,29,1,0,0,0,119,49,40,0,0,353,13,0,0

In [25]:
annual_aqi.reset_index(inplace=True)
# fips.reset_index(inplace=True)

In [26]:
# annual_aqi = pd.concat([annual_aqi, fips], axis=1)
annual_aqi = annual_aqi.merge(fips, on=['State', 'County'], how='left')
annual_aqi.drop(columns='index', inplace=True)
annual_aqi = annual_aqi.loc[:,~annual_aqi.columns.duplicated()]
annual_aqi = annual_aqi.drop_duplicates()
annual_aqi

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10,fips
0,Alabama,baldwin,2005,254,158,86,10,0,0,0,147,80,46,0,0,171,0,83,0,01003
21,Alabama,barbour,2005,59,35,23,1,0,0,0,119,68,47,0,0,0,0,59,0,01005
25,Alabama,clay,2005,282,176,96,10,0,0,0,136,84,46,0,0,191,0,91,0,01027
46,Alabama,colbert,2005,365,255,100,10,0,0,0,126,75,43,0,0,188,94,83,0,01033
66,Alabama,dekalb,2005,358,248,102,8,0,0,0,140,74,43,0,0,275,0,83,0,01049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335218,Wyoming,sublette,2020,366,297,64,4,1,0,0,151,61,44,0,0,355,0,11,0,56035
335239,Wyoming,sweetwater,2020,366,238,116,7,4,0,1,1250,76,46,0,5,253,0,7,101,56037
335260,Wyoming,teton,2020,366,318,36,7,5,0,0,161,54,42,0,0,329,0,37,0,56039
335281,Wyoming,uinta,2020,366,323,41,2,0,0,0,122,51,40,0,2,225,0,0,139,56041
335295,Wyoming,weston,2020,366,336,29,1,0,0,0,119,49,40,0,0,353,13,0,0,56045

In [27]:
annual_aqi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17003 entries, 0 to 335295
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State                                17003 non-null  object
 1   County                               17003 non-null  object
 2   Year                                 17003 non-null  int64
 3   Days with AQI                        17003 non-null  int64
 4   Good Days                            17003 non-null  int64
 5   Moderate Days                        17003 non-null  int64
 6   Unhealthy for Sensitive Groups Days  17003 non-null  int64
 7   Unhealthy Days                       17003 non-null  int64
 8   Very Unhealthy Days                  17003 non-null  int64
 9   Hazardous Days                       17003 non-null  int64
 10  Max AQI                              17003 non-null  int64
 11  90th Percentile AQI                  17003 non-null  int64
 12  Median AQI                           17003 non-null  int64
 13  Days CO                              17003 non-null  int64
 14  Days NO2                             17003 non-null  int64
 15  Days Ozone                           17003 non-null  int64
 16  Days SO2                             17003 non-null  int64
 17  Days PM2.5                           17003 non-null  int64
 18  Days PM10                            17003 non-null  int64
 19  fips                                 16824 non-null  object
dtypes: int64(17), object(3)
memory usage: 2.7+ MB

In [28]:
ak_fips

                      County   State  fips
23                anchorage   Alaska  None
24                   denali   Alaska  None
25     fairbanks north star   Alaska  None
26                   juneau   Alaska  None
27        ketchikan gateway   Alaska  None
...                      ...     ...   ...
21626  fairbanks north star   Alaska  None
21627                juneau   Alaska  None
21628       kenai peninsula   Alaska  None
21629     matanuska-susitna   Alaska  None
21630           north slope   Alaska  None

[169 rows x 3 columns]

In [29]:
# annual_aqi.loc[annual_aqi['County'] == 'Anchorage', 'fips'] = 2020
# annual_aqi.loc[annual_aqi['County'] == 'Denali', 'fips'] = 2068
# annual_aqi.loc[annual_aqi['County'] == 'Juneau', 'fips'] = 2110
# annual_aqi.loc[annual_aqi['County'] == 'Fairbanks North Star', 'fips'] = 2090
# annual_aqi.loc[annual_aqi['County'] == 'Matanuska‑Susitna', 'fips'] = 2170

In [30]:
annual_aqi['State'].value_counts()

California              854
Texas                   716
North Carolina          709
Ohio                    687
Indiana                 676
Pennsylvania            614
Florida                 609
Virginia                580
Georgia                 519
New York                509
Colorado                486
Wisconsin               483
Kentucky                478
Washington              476
Michigan                457
Illinois                426
Tennessee               402
Oklahoma                371
Oregon                  369
Louisiana               368
Missouri                353
Minnesota               332
South Carolina          323
Idaho                   304
Montana                 303
Alabama                 301
Iowa                    301
Wyoming                 285
New Mexico              273
New Jersey              261
Maryland                255
West Virginia           252
Utah                    222
Arkansas                218
Arizona                 211
Kansas                  210
Massachusetts           199
Mississippi             196
Maine                   176
Nebraska                174
North Dakota            158
Nevada                  150
South Dakota            146
Alaska                  131
Connecticut             128
New Hampshire           116
Vermont                  64
Hawaii                   60
Delaware                 48
Rhode Island             48
District Of Columbia     16
Name: State, dtype: int64

In [31]:
# annual_aqi.dropna(inplace=True)

In [32]:
# annual_aqi['fips'].astype(int)

In [33]:
# aqi_fips = annual_aqi.merge(fips, how='left', left_on='County', right_on='County', copy=False).drop_duplicates(['County', 'Year', 'Max AQI'])
# aqi_fips.reset_index(inplace=True)
# aqi_fips

In [34]:
# aqi_fips.dropna(inplace=True)

In [35]:
# aqi_fips[['State','County','fips']].sort_values(by='fips')

In [36]:
annual_aqi.describe()

,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
count,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000,17003.000000
mean,2012.392284,307.486914,233.443039,66.365112,6.369641,1.170499,0.094042,0.044580,129.077163,62.862377,37.275363,0.833794,6.292066,164.047697,16.560607,106.472740,13.280009
std,4.619643,90.654713,85.316289,52.558056,12.705652,6.495602,0.978375,0.667978,221.322193,21.737735,12.651962,10.357679,24.258920,120.550839,61.027177,107.953241,51.148791
min,2005.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2008.000000,261.000000,173.000000,26.000000,0.000000,0.000000,0.000000,0.000000,90.000000,50.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2012.000000,361.000000,249.000000,54.000000,2.000000,0.000000,0.000000,0.000000,115.000000,60.000000,39.000000,0.000000,0.000000,182.000000,0.000000,82.000000,0.000000
75%,2016.000000,365.000000,305.000000,96.000000,7.000000,0.000000,0.000000,0.000000,150.000000,74.000000,44.000000,0.000000,0.000000,244.000000,0.000000,172.000000,1.000000
max,2020.000000,366.000000,366.000000,315.000000,154.000000,252.000000,74.000000,37.000000,14043.000000,306.000000,200.000000,334.000000,365.000000,366.000000,366.000000,366.000000,366.000000

In [37]:
# aqi_fips[aqi_fips['fips'].isna()]

In [38]:
# fips[fips['County'] == 'Dekalb']

In [39]:
annual_aqi['State'].value_counts()

California              854
Texas                   716
North Carolina          709
Ohio                    687
Indiana                 676
Pennsylvania            614
Florida                 609
Virginia                580
Georgia                 519
New York                509
Colorado                486
Wisconsin               483
Kentucky                478
Washington              476
Michigan                457
Illinois                426
Tennessee               402
Oklahoma                371
Oregon                  369
Louisiana               368
Missouri                353
Minnesota               332
South Carolina          323
Idaho                   304
Montana                 303
Alabama                 301
Iowa                    301
Wyoming                 285
New Mexico              273
New Jersey              261
Maryland                255
West Virginia           252
Utah                    222
Arkansas                218
Arizona                 211
Kansas                  210
Massachusetts           199
Mississippi             196
Maine                   176
Nebraska                174
North Dakota            158
Nevada                  150
South Dakota            146
Alaska                  131
Connecticut             128
New Hampshire           116
Vermont                  64
Hawaii                   60
Delaware                 48
Rhode Island             48
District Of Columbia     16
Name: State, dtype: int64

In [40]:
annual_aqi_no_alaska = annual_aqi.dropna()
# annual_aqi_no_alaska.to_csv('./datasets/annual_aqi_allfips.csv')

In [41]:
# annual_aqi.to_csv('./datasets/annual_aqi_missingfips.csv')

In [42]:
annual_aqi_haz_agg = annual_aqi[['Year', 'State', 'County',
            'Hazardous Days']].groupby(by=['Year', 'State', 
                                           'County']).agg({'Hazardous Days': ['mean']}).sort_values(('Hazardous Days', 'mean'), ascending=False)
                                                           

annual_aqi_haz_agg

                           Hazardous Days
                                     mean
Year State      County
2006 Arizona    pinal                37.0
2020 California mono                 26.0
2016 California mono                 24.0
2007 Arizona    pinal                24.0
2017 Montana    missoula             18.0
...                                   ...
2010 Georgia    rockdale              0.0
                sumter                0.0
                walker                0.0
                washington            0.0
2020 Wyoming    weston                0.0

[17003 rows x 1 columns]

In [43]:
annual_aqi_no_dc = annual_aqi[annual_aqi['State'] != 'District Of Columbia']

In [44]:
annual_aqi_no_dc.columns

Index(['State', 'County', 'Year', 'Days with AQI', 'Good Days',
       'Moderate Days', 'Unhealthy for Sensitive Groups Days',
       'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI', 'Median AQI', 'Days CO', 'Days NO2',
       'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10', 'fips'],
      dtype='object')

In [45]:
def rename_cols(string, columns):
    cols = []
    for col in columns:
        col = str(col)
        new_col = col+'_'+string
        cols.append(new_col)
    return cols

def unstack_pivots(df, col1, col2, col3, aggfunc):
    new_df = df.groupby([col1, col2]).agg({col3: [aggfunc]})
    pivot = new_df.unstack(0).T
    pivot.columns = rename_cols(f'{col3}', pivot.columns)
    pivot.columns = pivot.columns.to_flat_index()
    pivot.index = pivot.index.to_flat_index()
    pivot.index = [list(row)[2] for row in pivot.index]
    return pivot
    
def combine_pivots(df, col1, col2, list_cols, aggfunc):
    combined = []
    for col in list_cols:
        new_pivot = unstack_pivots(df, col1, col2, col, aggfunc)
        combined.append(new_pivot)
    return pd.concat(combined, axis=1)

# annual_aqi_states_year = annual_aqi_no_dc.groupby(['State', 'Year']).agg({'Good Days': ['mean'],
#                                                         'Moderate Days': ['mean'],
#                                                         'Unhealthy for Sensitive Groups Days': ['mean'],
#                                                         'Unhealthy Days': ['mean'],
#                                                         'Very Unhealthy Days': ['mean'],
#                                                         'Hazardous Days': ['mean'],
#                                                         'Days CO': ['mean'],
#                                                         'Days NO2': ['mean'],
#                                                         'Days Ozone': ['mean'],
#                                                         'Days SO2': ['mean'],
#                                                         'Days PM2.5': ['mean'],
#                                                         'Days PM10': ['mean']})
# # annual_aqi_states_year.reset_index(inplace=True)
# annual_aqi_states_year.unstack(0).T

In [46]:
list_cols = ['Good Days',
       'Moderate Days', 'Unhealthy for Sensitive Groups Days',
       'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI', 'Median AQI', 'Days CO', 'Days NO2',
       'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10']

In [47]:
new_pivot = unstack_pivots(annual_aqi_no_dc, 'State', 'Year', 'Good Days', 'mean')
new_pivot.fillna(0.0, inplace=True)
new_pivot = new_pivot.T
#     new_pivot.columns = new_pivot['State']
pct_change = new_pivot.pct_change()
# aqi_pct_change_list.append(pct_change)
pct_change

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
2005_Good Days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006_Good Days,-0.058392,0.122579,-0.081406,0.117372,-0.052920,-0.009048,0.100445,0.095491,-0.015349,-0.056552,...,0.107781,0.044525,0.105564,-0.098690,0.083172,0.009091,-0.082728,0.153792,0.209677,-0.068794
2007_Good Days,0.015096,0.009346,0.010654,0.140221,-0.001103,-0.094587,0.000000,0.041162,0.043625,-0.016227,...,0.198043,-0.144466,0.037405,0.028239,0.101562,-0.019984,0.090780,-0.087339,-0.016177,0.054724
2008_Good Days,0.111492,0.008547,0.084663,0.058252,-0.067992,-0.045312,0.068169,0.067442,0.014376,0.216421,...,0.101394,0.197918,0.041687,0.091307,-0.083080,0.152212,0.040042,0.206675,0.125756,0.084050
2009_Good Days,0.185866,0.010672,0.196004,0.089067,0.082132,0.105877,0.108707,0.302832,0.096475,0.255189,...,0.027729,0.320017,0.037893,0.103206,0.308287,0.098218,0.002188,0.059647,-0.004642,0.131835
2010_Good Days,-0.177474,0.240994,-0.037788,-0.141081,0.072614,-0.040115,-0.071707,-0.043478,-0.076840,-0.123633,...,-0.020377,-0.165087,0.033165,0.045064,-0.007883,-0.163033,0.095736,-0.000943,-0.059411,0.007770
2011_Good Days,0.041813,0.059685,-0.047954,0.010000,-0.129288,-0.035143,-0.068313,0.311189,0.039857,-0.011741,...,0.026965,0.063166,-0.123951,0.045354,-0.300227,0.161847,-0.051710,0.060120,-0.012964,0.031351
2012_Good Days,0.170037,0.099362,0.049066,0.065390,0.047359,0.039710,0.005076,-0.050667,0.105258,0.174309,...,-0.139535,-0.013707,0.098663,0.055537,0.238443,0.043513,0.017434,0.015044,-0.042071,-0.052749
2013_Good Days,0.118850,-0.056549,0.122930,0.306976,-0.056201,0.089890,-0.042088,0.115169,0.020536,0.148119,...,0.073670,0.062507,0.052774,-0.017013,-0.002947,0.067195,-0.069388,0.124493,0.061212,0.156678
2014_Good Days,-0.050889,-0.106045,0.040546,0.070583,0.014936,0.087876,0.103691,-0.041562,-0.018805,-0.074212,...,0.100690,0.018703,0.009813,0.207692,0.023645,0.038887,0.053293,-0.027469,0.205343,0.031416
2015_Good Days,0.020302,-0.056160,0.117960,0.003158,0.019876,-0.039539,-0.005839,-0.006570,0.049861,0.097561,...,-0.024308,-0.017238,0.030967,-0.003640,-0.014437,-0.008936,-0.025929,0.001712,0.032852,-0.013252
2016_Good Days,0.005102,0.149796,-0.021863,0.047619,0.088447,0.008381,0.046983,0.095238,-0.022467,-0.025339,...,0.064308,-0.075944,-0.037613,-0.051370,0.092773,-0.001271,0.084335,0.117508,0.001743,0.091524
2017_Good Days,0.063452,0.036814,-0.074182,-0.066116,-0.045858,-0.048921,0.107598,0.030193,-0.020285,0.001547,...,-0.024936,0.305763,0.043433,-0.097172,-0.008937,0.069988,-0.110196,0.033656,0.105278,-0.097363
2018_Good Days,0.040629,0.010477,0.053534,-0.054204,0.006342,-0.065050,-0.024401,0.014068,0.027467,0.050279,...,-0.024590,0.099350,0.010612,-0.001044,-0.028855,-0.000869,0.047203,0.016644,-0.048019,-0.008097
2019_Good Days,-0.025012,-0.047043,0.086682,-0.074044,0.200402,0.094148,0.044832,-0.016185,-0.008775,-0.045938,...,0.028235,0.013343,0.025481,0.191781,0.026927,0.021734,0.047351,0.018190,0.014195,0.160857
2020_Good Days,0.045264,-0.093089,-0.033924,0.138643,-0.118779,-0.053592,-0.011743,0.129260,0.018526,0.122745,...,0.060477,0.057758,0.002901,0.023511,-0.039783,0.026042,-0.019055,-0.009826,-0.011279,-0.008765

In [48]:
aqi_pct_change_list = []
for col in list_cols:
    new_pivot = unstack_pivots(annual_aqi_no_dc, 'State', 'Year', col, 'mean')
    new_pivot.fillna(0.0, inplace=True)
    new_pivot = new_pivot.T
#     new_pivot.columns = new_pivot['State']
    pct_change = new_pivot.pct_change()
    pct_change = pct_change.iloc[1: , :]
    pct_change = pct_change.T
    pct_change.fillna(0.0, inplace=True)
    pct_change.replace(np.inf, 0.0, inplace=True)
    aqi_pct_change_list.append(pct_change)
    
aqi_pct_change = pd.concat(aqi_pct_change_list, axis=1)

In [50]:
aqi_pct_change.reset_index(inplace=True)
aqi.rename({'index': 'State'}, axis=1)
aqi_pct_change

NameError: name 'aqi' is not defined

In [ ]:
aqi_pct_change.to_csv('health_issues_per_change/aqi_pct_change.csv')

In [ ]:
annual_aqi_by_state = combine_pivots(annual_aqi_no_dc, 'State', 'Year', list_cols, 'mean')
annual_aqi_by_state

In [ ]:
annual_aqi_by_state.reset_index(inplace=True)
annual_aqi_by_state.rename({'index':'State'}, axis=1, inplace=True)
annual_aqi_by_state

In [ ]:
# code thanks to https://gist.github.com/rogerallen/1583593 & 
# https://datasciencity.com/2020/05/06/how-to-map-a-dictionary-to-a-data-frame-column-in-python-mapping-us-state-abbreviations-to-long-forms/

states_to_abrv = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}
 
annual_aqi_by_state["state_abrv"] = annual_aqi_by_state['State'].map(states_to_abrv)
annual_aqi_by_state

In [ ]:
# plt.figure(figsize=(25,25))
# sns.pairplot(annual_aqi_by_state[1:6], corner=True)
# plt.tight_layout();

In [ ]:
annual_aqi_by_state.info()

In [ ]:
list(annual_aqi_by_state.columns)

More info here: https://aqs.epa.gov/aqsweb/documents/AQS_Data_Dictionary.html

"AQI
The Air Quality Index for the day for the pollutant, if applicable. The air quality index is a unitless measure of the amount of pollutant that can be used to relate the pollutant to the healthy levels and indicate possible health concerns with elevated levels. The Air Quality Index (AQI) is a measure for reporting daily air quality. It focuses on health effects that may be experienced within a few hours or days after breathing polluted air. AQI is calculated for the following major air pollutants regulated by the Clean Air Act: Ozone, PM 2.5, PM 10, carbon monoxide, sulfur dioxide, and nitrogen dioxide. The AQI is a mapping from pollutant concentrations to the common index. The index is based on defining seven levels of concentration/index values that are classified as follows:

Good (with AQI values from 0 to 50),
Moderate (with AQI values from 51 to 100),
Unhealthy for Sensitive Groups (with AQI values from 101 to 150),
Unhealthy (with AQI values from 151 to 200),
Very Unhealthy (with AQI values from 201 to 300),
Hazardous (with AQI values above 301).
The upper and lower bounds of each AQI level classification are called “breakpoints” for the level. The EPA defines specific pollutant concentrations to be associated with each breakpoint; e.g. for Ozone, the “Moderate” classification level has the concentration of 0.060 ppm associated with its lower AQI value of 50, and the concentration of 0.075 associated with its higher AQI value of 100. AQI values in this concentration range are then computed by linear interpolation."

https://ww2.arb.ca.gov/resources/inhalable-particulate-matter-and-health:

"What is Particulate Matter?
Airborne particulate matter (PM) is not a single pollutant, but rather is a mixture of many chemical species. It is a complex mixture of solids and aerosols composed of small droplets of liquid, dry solid fragments, and solid cores with liquid coatings. Particles vary widely in size, shape and chemical composition, and may contain inorganic ions, metallic compounds, elemental carbon, organic compounds, and compounds from the earth’s crust. Particles are defined by their diameter for air quality regulatory purposes. Those with a diameter of 10 microns or less (PM10) are inhalable into the lungs and can induce adverse health effects. Fine particulate matter is defined as particles that are 2.5 microns or less in diameter (PM2.5). Therefore, PM2.5 comprises a portion of PM10.

What is the Difference Between PM10 and PM2.5?
PM10 and PM2.5 often derive from different emissions sources, and also have different chemical compositions. Emissions from combustion of gasoline, oil, diesel fuel or wood produce much of the PM2.5 pollution found in outdoor air, as well as a significant proportion of PM10. PM10 also includes dust from construction sites, landfills and agriculture, wildfires and brush/waste burning, industrial sources, wind-blown dust from open lands, pollen and fragments of bacteria.

PM may be either directly emitted from sources (primary particles) or formed in the atmosphere through chemical reactions of gases (secondary particles) such as sulfur dioxide (SO2), nitrogen oxides (NOX), and certain organic compounds. These organic compounds can be emitted by both natural sources, such as trees and vegetation, as well as from man-made (anthropogenic) sources, such as industrial processes and motor vehicle exhaust. The relative sizes of PM10 and PM2.5 particles are compared in the figure below."

https://www.airnow.gov/sites/default/files/2021-03/air-quality-guide_ozone_2015.pdf:

"What is ozone?
Ozone is a colorless gas that can be good or bad,
depending on where it is. Ozone in the stratosphere
is good because it shields the earth from the sun’s
ultraviolet rays. Ozone at ground level, where we breathe,
is bad because it can harm human health.
Ozone forms when two types of pollutants (VOCs and
NOx) react in sunlight. These pollutants come from
sources such as vehicles, industries, power plants, and
products such as solvents and paints." 

https://www.epa.gov/naaqs/sulfur-dioxide-so2-primary-air-quality-standards:

"Sulfur Dioxide (SO2) Primary Air Quality Standards
The Clean Air Act requires EPA to set national ambient air quality standards (NAAQS) for sulfur dioxide and five other pollutants considered harmful to public health and the environment (the other pollutants are ozone, particulate matter, nitrogen dioxide, carbon monoxide, and lead). The law also requires EPA to periodically review the standards to ensure that they provide adequate health and environmental protection, and to update those standards as necessary."

For reference table of all air pollutants included in our dataset:
https://www.epa.gov/criteria-air-pollutants/naaqs-table


|column name|value|
|-----------|-----|
|State|Full US State Names| 
|2005(-2020)_Good Days|# of 'Good Days' per year on AQI|
|2005(-2020)_Moderate Days|# of 'Moderate Days' per year on AQI|
|2005(-2020)_Unhealthy for Sensitive Groups Days|# of 'Unhealthy for Sensitive Groups Days' per year on AQI|
|2005(-2020)_Unhealthy Days|# of 'Unhealthy Days' per year on AQI|
|2005(-2020)_Very Unhealthy Days|# of 'Very Unhealthy Days' per year on AQI|
|2005(-2020)_Hazardous Days|# of 'Hazardous Days' per year on AQI|
|2005(-2020)_Max AQI|Max AQI per year|
|2005(-2020)_90th Percentile AQI|90th Percentile AQI per year (The sample value in the summarized sample set where 90% of the values in that set are less than or equal to it. (For ozone, based on valid daily maxima; for PM2.5, based on seasonal and non-seasonal algorithms)|
|2005(-2020)_Median AQI|Median AQI per year|
|2005(-2020)_Days CO|# of 'Days CO' per year on AQI|
|2005(-2020)_Days NO2|# of 'Days NO2' per year on AQI|
|2005(-2020)_Days Ozone|# of 'Days Ozone' per year on AQI|
|2005(-2020)_Days SO2|# of 'Days SO2' per year on AQI|
|2005(-2020)_Days PM2.5|# of 'Days PM2.5' per year on AQI|
|2005(-2020)_Days PM10|# of 'Days PM10' per year on AQI|
|state_abrv|US State Abbreviations|

In [ ]:
# annual_aqi_by_states = annual_aqi_no_dc.groupby('State').agg({'Good Days': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Moderate Days': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Unhealthy for Sensitive Groups Days': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Unhealthy Days': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Very Unhealthy Days': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Hazardous Days': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Days CO': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Days NO2': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Days Ozone': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Days SO2': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Days PM2.5': ['count', 'mean', 'min', 'max', 'sum'],
#                                                         'Days PM10': ['count', 'mean', 'min', 'max', 'sum']})
# annual_aqi_by_states.reset_index(inplace=True)
# annual_aqi_by_states

In [ ]:
# fips_rows = []
# for i, row in annual_aqi_by_states.iterrows():
#     fips_row = {
#         'State': row[('State')][0]
#     }
#     fips_rows.append(fips_row)

# fips_rows[:5]

In [ ]:
# code from https://pypi.org/project/addfips/

# af = addfips.AddFIPS()
# for row in fips_rows:
#     af.add_state_fips(row, state_field='State')
    
# fips_rows[:5]

In [ ]:
# state_fips = pd.DataFrame(fips_rows)
# state_fips

In [ ]:
# annual_aqi_by_states = annual_aqi_by_states.merge(state_fips, left_on=('State', ), right_on='State')
# annual_aqi_by_states.drop('State', axis=1, inplace=True)
# annual_aqi_by_states

In [ ]:
annual_aqi_by_state.to_csv('./datasets/annual_aqi_by_state.csv')

In [ ]:
annual_aqi_vud_agg = annual_aqi[['Year', 'State', 'County', 'Very Unhealthy Days'
            ]].groupby(by=['Year', 'State', 
                                           'County']).agg({'Very Unhealthy Days': ['mean']}).sort_values(('Very Unhealthy Days', 'mean'), ascending=False)
                                                           

annual_aqi_vud_agg.plot(kind='scatter', x=('Very Unhealthy Days', 'mean'), y='Very Unhealthy Days')

In [ ]:
# https://geopandas.org/docs/user_guide/mapping.html

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

cities = geopandas.read_file(geopandas.datasets.get_path('naturalearth_cities'))

cities.head()

In [ ]:
# https://plotly.com/python/choropleth-maps/

from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import pandas as pd
# df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
#                    dtype={"fips": str})

import plotly.express as px

fig = px.choropleth(annual_aqi, geojson=counties, locations='fips', color=('Hazardous Days'),
                           color_continuous_scale='darkmint',
                           range_color=(0, 12),
                           scope="usa",
                           labels={'Hazardous Days':'mean'}
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [ ]:
# code from https://plotly.com/python/choropleth-maps/

import plotly.graph_objects as go


fig = go.Figure(data=go.Choropleth(
    locations=annual_aqi_by_state['state_abrv'], # Spatial coordinates
    z = annual_aqi_by_state.mean(axis=1), # Data to be color-coded
    locationmode = 'USA-states', # set of locations match entries in `locations`
    colorscale = 'Reds',
    colorbar_title = "Mean",
#     hovertext=lead_states_by_year['2006_Lead Sample Measure (mg/L)'],
    marker_line_color='white'
))

fig.update_layout(
    title_text = 'Annual AQI Mean by State',
    geo_scope='usa', # limit map scope to USA
)


fig.show()